# Generated by Django 5.1.4 on 2025-01-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default="Hi I'm new!", max_length=200, null=True),
        ),
    ]
